# Generated by Django 3.0.4 on 2020-08-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='keys',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
