# Generated by Django 3.0.4 on 2020-08-18 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200816_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
